# Generated by Django 4.2.7 on 2023-12-04 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('description', models.TextField(max_length=500, null=True)),
                ('slug', models.CharField(max_length=150)),
                ('image', models.ImageField(null=True, upload_to='pet-img/')),
                ('phone_number', models.IntegerField(max_length=9, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('video', models.FileField(blank=True, max_length=350, null=True, upload_to='pet-videos/')),
                ('public_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
